### GET /
GET http://localhost:5003/

### POST REGISTER USER AUTH/REGISTER
POST http://localhost:5003/auth/register
Content-Type: application/json

{
    "name": "Test User",
    "username": "test@username.com",
    "password": "user1pass"
}

### POST LOGIN USER AUTH/LOGIN
POST http://localhost:5003/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "secret123"
}